### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by happilymarrieddad** [2tvenom/myreplication#5]
Hey guys,

I can get replication to work just fine with npm's mysql-events package but I can't for the life of me getting this package to work. Here are some screenshots to show what is going on.

![selection_074](https://user-images.githubusercontent.com/6416323/35747038-187ee5ea-0806-11e8-8d30-4aec625ec33d.png)
![selection_075](https://user-images.githubusercontent.com/6416323/35747040-1a77bfc0-0806-11e8-904d-7723a7ab1022.png)
![selection_076](https://user-images.githubusercontent.com/6416323/35747043-1c039422-0806-11e8-94cd-37e266a64412.png)

**Comment by 2tvenom** [comment]
mysql version?

**Comment by happilymarrieddad** [comment]
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper

**Comment by happilymarrieddad** [comment]
server-id		= 1
log_bin			= /var/log/mysql/mysql-bin.log
expire_logs_days	= 10
max_binlog_size   = 100M
binlog_do_db		= fusion
binlog_format = row

**Comment by 2tvenom** [comment]
you check in another version?

**Comment by happilymarrieddad** [comment]
maybe it has something to do with information_schema... This is from my error log but I didnt try to log in as root

2018-02-02T17:05:58.731836Z 14 [Note] Aborted connection 14 to db: 'information_schema' user: 'root' host: 'localhost' (failed on flush_net())

**Comment by 2tvenom** [comment]
can you check with root privilege?

**Comment by happilymarrieddad** [comment]
no it doesn't work with root either. I used 

CREATE USER 'fusiontest'@'%' IDENTIFIED BY 'test';
GRANT ALL ON *.* TO 'fusiontest'@'%';
FLUSH PRIVILEGES;

**Comment by happilymarrieddad** [comment]
I just tried root and no go.

**Comment by happilymarrieddad** [comment]
I can't downgrade aws mysql because it's a live server 24/7

**Comment by 2tvenom** [comment]
you can receive master status?

**Comment by 2tvenom** [comment]
in event.(type) switch you have default case?

**Comment by happilymarrieddad** [comment]
no but I added a default case and nothing came through

Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SHOW MASTER STATUS;
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000002 |     2580 | fusion       |                  |                   |
+------------------+----------+--------------+------------------+-------------------+
1 row in set (0.00 sec)

mysql>

**Comment by happilymarrieddad** [comment]
```
  mysql  ll
total 20K
-rw-r----- 1 mysql mysql 9.3K Feb  2 10:07 mysql-bin.000001
-rw-r----- 1 mysql mysql 2.6K Feb  2 10:42 mysql-bin.000002
-rw-r----- 1 mysql mysql   64 Feb  2 10:07 mysql-bin.index
☁  mysql  
☁  mysql  
☁  mysql  

```

**Comment by happilymarrieddad** [comment]
also the replication for sure is working because nodejs is picking it up

**Comment by happilymarrieddad** [comment]
https://www.npmjs.com/package/mysql-events

This package is picking it up.. I don't really like node anymore and this is the last part I need to make the move to Go =)

**Comment by 2tvenom** [comment]
i need check this mysql version

**Comment by happilymarrieddad** [comment]
@2tvenom I got it to work. Thanks!

**Comment by yogeshkad786** [comment]
@happilymarrieddad I m too facing the same issue while adding additional node to mysql cluster.
Can you please share what is the fix? 
[Note] Start binlog_dump to master_thread_id(286) slave_server(7), pos(, 4)
 [Note] Aborted connection 286 to db: 'unconnected' user: 'mysql_innodb_cluster_r1722846580' host: 'xxxxxxxxxxxx' (failed on flush_net())

**Comment by happilymarrieddad** [comment]
@yogeshkad786 Hey, what are your settings? Your binlog settings, user permissions?
